[package]
name = "twitch_oauth2"
version = "0.6.1"
authors = ["Emil Gardström <emil.gardstrom@gmail.com>"]
edition = "2018"
repository = "https://github.com/Emilgardis/twitch_oauth2"
license = "MIT OR Apache-2.0"
description = "Oauth2 for Twitch endpoints"
keywords = ["oauth", "twitch", "async", "asynchronous"]
documentation = "https://docs.rs/twitch_oauth2/0.6.1"
readme = "README.md"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = []
reqwest_client = ["reqwest"]
surf_client_curl = ["surf_client", "surf/curl-client"]
surf_client = ["surf", "http-types", "http-types/hyperium_http"]
mock_api = []
all = ["surf_client_curl", "reqwest_client"]

[dependencies]
thiserror = "1.0.29"
displaydoc = "0.2.3"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
async-trait = "0.1.51"
http = "0.2.5"
surf = { version = "2.3.1", optional = true, default-features = false }
reqwest = { version = "0.11.4", optional = true, default-features = false }
http-types = { version = "2.12.0", optional = true }
once_cell = "1.8.0"
aliri_braid = "0.1.9"
url = "2.2.2"
base64 = "0.13.0"
rand = "0.8.4"

[dev-dependencies]
tokio = { version = "1.12.0", features = ["rt-multi-thread", "macros", "test-util"] }
dotenv = "0.15.0"
anyhow = "1.0.44"
reqwest = "0.11.4"
surf = "2.3.1"
rpassword = "5.0.1"

[[example]]
name = "user_token"
path = "examples/user_token.rs"
required-features = ["surf_client"]

[[example]]
name = "app_access_token"
path = "examples/app_access_token.rs"
required-features = ["surf_client"]

[[example]]
name = "auth_flow"
path = "examples/auth_flow.rs"
required-features = ["reqwest_client"]


[[example]]
name = "mock_app"
path = "examples/mock_app.rs"
required-features = ["reqwest_client", "mock_api"]

[[example]]
name = "mock_user"
path = "examples/mock_user.rs"
required-features = ["reqwest_client", "mock_api"]

[package.metadata.docs.rs]
features = ["all", "mock_api"]
rustc-args = ["--cfg", "nightly"]
