[package]
name = "twitch_oauth2"
version = "0.5.0-alpha.5"
authors = ["Emil Gardström <emil.gardstrom@gmail.com>"]
edition = "2018"
repository = "https://github.com/Emilgardis/twitch_oauth2"
license = "MIT OR Apache-2.0"
description = "Oauth2 for Twitch endpoints"
keywords = ["oauth", "twitch", "async", "asynchronous"]
documentation = "https://docs.rs/twitch_oauth2/0.4.1"
readme = "README.md"
build = "build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = []
reqwest_client = ["oauth2/reqwest"]
surf_client = ["surf","http-types", "http-types/hyperium_http"]
all = ["surf_client", "reqwest_client"]

[dependencies]
oauth2 = { version = "4.0.0", features = [], default-features = false }
thiserror = "1.0.24"
displaydoc = "0.2.1"
serde = "1.0.125"
serde_json = "1.0.64"
async-trait = "0.1.50"
http = "0.2.4"
surf = { version = "2.1.0", optional = true }
http-types = { version = "2.9.0", optional = true }

[dev-dependencies]
tokio = { version = "1.5.0", features = ["rt-multi-thread", "macros", "test-util"] }
dotenv = "0.15.0"
anyhow = "1.0.40"

[build-dependencies]
version_check = "0.9.3"

[[example]]
name = "user_token"
path = "examples/user_token.rs"
required-features = ["surf_client"]

[package.metadata.docs.rs]
features = ["reqwest_client", "surf_client"]
